language: python
python:
  - 2.6
  - 2.7
env:
  - SETUP_COMMAND="install"
  - SETUP_COMMAND="build"
  - SETUP_COMMAND="-q bdist_egg --dist-dir /tmp/easy_install/virtual-node"
install:
  - python setup.py $SETUP_COMMAND
script:
  - nosetests
